<?xml version="1.0"?>
<package format="3">
  <name>airship_utils</name>
  <version>0.1.0</version>
  <description>灵云01号飞艇伴飞电脑通用工具库（数学工具函数），演示 gtest 单元测试写法</description>
  <maintainer email="dev@lingyun.local">Lingyun Airship Team</maintainer>
  <license>Proprietary</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>
  <test_depend>ament_cmake_gtest</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>